name: Deploy Cloud Function

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true

      - name: Deploy Function
        run: |
          gcloud functions deploy nodejs-http-function \
            --entry-point helloGET \
            --runtime nodejs18 \
            --region=us-east1 \
            --source=. \
            --trigger-http 

      - name: Install Dependencies
        run: npm install
